[workspace.package]
name = "cyphers"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
chacha20 = "0.9.1"
hextool = "0.1.3"
k256 = {version = "0.13.4"}
sha2 = "0.10.9"

[workspace]
resolver = "3"
members = ["app", "macros"]
