[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
k256.workspace = true
sha2.workspace = true
chacha20.workspace = true
hextool.workspace = true
macros = {path = "../macros"}
base64 = "0.22.1"
rand = "0.9.2"
clap = { version = "4.5.53", features = ["derive"] }

