[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
k256.workspace = true
sha2.workspace = true
chacha20.workspace = true
hextool.workspace = true
macros = {path = "../macros"}

